export const GET_LOAD_DATA = 'GET_LOAD_DATA'
export const SUCCESS_LOAD_DATA = 'GET_LOAD_DATA_SUCCESS'
export const ERROR_LOAD_DATA = 'ERROR_LOAD_DATA'
export const CLEAR_DATA = 'CLEAR_DATA'

export const CHANGE_SELECT_TOKEN = 'CHANGE_SELECT_TOKEN'
