export const GET_FLIGHTS = 'GET_FLIGHTS'
export const SUCCESS_LOAD_FLIGHTS = 'SUCCESS_LOAD_FLIGHTS'
export const ERROR_LOAD_FLIGHTS = 'ERROR_LOAD_FLIGHTS'
export const CHANGE_ACTIVE_COMPANY = 'CHANGE_ACTIVE_COMPANY'
